version: '3.9'

services:
  expensafe-app:
    build: .
    container_name: expensafe_app
    ports:
      - "8185:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: expensafe_postgres
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
