spring:
  application:
    name: expensafe-core
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost}:${POSTGRES_DB_PORT:5423}/${POSTGRES_DB_NAME:mydb}
    username: ${POSTGRES_DB_USER:myuser}
    password: ${POSTGRES_DB_PASSWORD:mypass}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8185

app:
  cors:
    allowed-origins:
      - http://localhost:8082   # Vue running on
      - http://localhost:5173   # Vue dev server